"""temp_nullable

Revision ID: 99c3c5b200b3
Revises: f1fd18055f03
Create Date: 2026-08-14 19:16:55.160107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c3c5b200b3'
down_revision: Union[str, Sequence[str], None] = 'f1fd18055f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
